Artist screen
PWiley/Soundsbinder pull request #6
Opened 2022-02-17 14:12 UTC by PWiley

WIP ArtistCell

2022-02-22 19:08 UTC, Asavarkhul requested changes

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +    // MARK: - Private Properties
missing space after mark

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +
useless line

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +        artistCell.shadowDecorate()
This is not the responsibility of the controller to build rendering. The cell should do it itself.

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +        guard indexPath.item < catalogArtists.count else {
the test should be done on viewModel side

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +
useless line

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsRepository.swift
> +
useless line

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsRepository.swift
> +            //assertionFailure(error.localizedDescription)
dead code

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsViewController.swift
> +            DispatchQueue.main.async {
Dispatch should be done on viewModel side

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +        // label.adjustsFontSizeToFitWidth = true
dead code

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +
useless line

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +
useless line

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +
useless line

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +    func shadowDecorate() {
should be private

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +
useless line

2022-02-22 19:08 UTC, Asavarkhul commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Image/imageProvider.swift
> +//final class ImageProvider {
Dead code

2022-02-23 09:43 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +    // MARK: - Private Properties
ok

2022-02-23 09:43 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +
ok

2022-02-23 09:44 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +        artistCell.shadowDecorate()
ok

2022-02-23 09:46 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +        guard indexPath.item < catalogArtists.count else {
ok

2022-02-23 09:49 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/ArtistsDataSource.swift
> +
ok

2022-02-23 10:04 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +
ok

2022-02-23 10:04 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +    func shadowDecorate() {
not anymore used.

2022-02-23 10:04 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Cell/ ArtistCell.swift
> +
not anymore used.

2022-02-23 10:11 UTC, PWiley commented on SoundsBinder/SoundsBinder/Sources/App/Artists/Image/imageProvider.swift
> +//final class ImageProvider {
delete class

2022-02-25 09:57 UTC, closed without merging